### Test with a know user, good level and time
POST {{baseUrl}}/leaderboard/add
Content-Type: application/json

{
  "username": "nitroc",
  "level": 1,
  "time": 99
}

###log in a existing user
# @name michele
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username":"michele",
  "password":"michele"
}

###check if the logged user can ad a new time to the leaderboard
POST {{baseUrl}}/leaderboard/add
Content-Type: application/json
Authorization: {{micheleToken}}

{
  "username": "michele",
  "level": 6,
  "time": 100
}

###check if the non existing user can ad a new time to the leaderboard (he shouldn't be able to)
POST {{baseUrl}}/leaderboard/add
Content-Type: application/json

{
  "username": "michele",
  "level": 1,
  "time": 100
}

### Test get leaderboard sorted
GET {{baseUrl}}/leaderboard
